### ISSUE TITLE
Crashes with group

### ISSUE THREAD

**Issue by equalsraf** [stepancheg/rust-protobuf#138]
Cheers, .the following minimal example is crashing for me

```protobuf
message Something {
        optional group Info = 12 {
                optional string description = 13;
        } 
}
```

Trace, using master ()

```log
$ protoc --rust_out . test.proto 
thread '<main>' panicked at 'unknown named type: TYPE_GROUP', src/lib/codegen.rs:430
stack backtrace:
   1:     0x5654bfe54b40 - sys::backtrace::tracing::imp::write::h3674b5beb3547da0Unt
   2:     0x5654bfe56f15 - panicking::log_panic::_<closure>::closure.39701
   3:     0x5654bfe56961 - panicking::log_panic::h1d8a2e79e18f3ea01nx
   4:     0x5654bfe4d613 - sys_common::unwind::begin_unwind_inner::hf13a63e36305e192Ygs
   5:     0x5654bfe4d9a8 - sys_common::unwind::begin_unwind_fmt::h4ca44836eade1bea4fs
   6:     0x5654bfdd793a - codegen::field_type_name::h13fc2f7520c8abccItu
                        at /home/raf/Code/rust-protobuf/<std macros>:8
   7:     0x5654bfdd8b99 - codegen::_<impl>::parse::h02e968fb67b76930CDu
                        at src/lib/codegen.rs:482
   8:     0x5654bfdf6db9 - codegen::_<impl>::new::_<closure>::closure.24450
                        at src/lib/codegen.rs:1417
   9:     0x5654bfdf6d43 - ops::impls::_<impl>::call_once::call_once::h9552227763524705060
                        at src/libcore/ops.rs:1795
  10:     0x5654bfdf6ce0 - option::_<impl>::map::map::h11219711743242362464
                        at src/libcore/option.rs:426
  11:     0x5654bfdf6c7e - iter::_<impl>::next::next::h12089330511512178293
                        at src/libcore/iter.rs:2259
  12:     0x5654bfdf6877 - vec::_<impl>::from_iter::from_iter::h17632591381221447839
                        at src/libcollections/vec.rs:1225
  13:     0x5654bfdf67f9 - iter::Iterator::collect::collect::h13282404226433077471
                        at src/libcore/iter.rs:809
  14:     0x5654bfdf65a4 - codegen::_<impl>::new::hc1ceeafd4bdaf927Shw
                        at src/lib/codegen.rs:1416
  15:     0x5654bfe262fd - codegen::gen::hc0550010112dab97mcx
                        at src/lib/codegen.rs:2044
  16:     0x5654bfe2bf46 - compiler_plugin::plugin_main::h8328eb6c5cdb92be6hx
                        at src/lib/compiler_plugin.rs:19
  17:     0x5654bfe2bd7f - codegen::protoc_gen_rust_main::h49667e7285c062eaIhx
                        at src/lib/codegen.rs:2070
  18:     0x5654bfd57398 - main::hbb170ffd3fa5f18fgaa
                        at src/protoc-gen-rust.rs:9
  19:     0x5654bfe566a4 - sys_common::unwind::try::try_fn::h1717139548377829537
  20:     0x5654bfe54078 - __rust_try
  21:     0x5654bfe5633f - rt::lang_start::hbeb1bf39635abdcc9kx
  22:     0x5654bfd573d9 - main
  23:     0x7f5813f5c67f - __libc_start_main
                        at /builddir/glibc-2.22/csu/libc-start.c:289
  24:     0x5654bfd57288 - _start
                        at ../sysdeps/x86_64/start.S:108
  25:                0x0 - <unknown>
--rust_out: protoc-gen-rust: Plugin failed with status code 101.
```

Seems groups are not supported, is this correct?

**Comment by stepancheg** [comment]
[groups](https://developers.google.com/protocol-buffers/docs/proto#groups) were deprecated even before protobuf was released to public. So they are not implemented in rust-protobuf.

Are you sure you need `group`, and not `oneof`?

**Comment by equalsraf** [comment]
Not exactly my choice, seems it is still used in a couple places, here is the offending [proto file](https://github.com/egirault/googleplay-api/blob/master/googleplay.proto#L77), oh well.

**Comment by stepancheg** [comment]
Do you actually need those fields?

It is easy to patch rust-protobuf to just ignore `group` fields, but full support implenetation is a significant amount of work.

**Comment by equalsraf** [comment]
Good point, I think I might be able to get away with ignoring those fields.

**Comment by stepancheg** [comment]
Done in 3bbd755390c3b1dd10177bb4f9ae79ca964f7132. group fields are ignored during codegeneration now.

**Comment by equalsraf** [comment]
Works like a charm, thanks.

**Comment by equalsraf** [comment]
Looks like I spoke a bit too soon the generator worked, but now protobuf::parse_from_reader fails with

    WireError(\"unknown wire type: 3\")")

**Comment by stepancheg** [comment]
Now protobuf ignores group fields while parses a stream. Hope it helps you. Please note, I haven't tested this code. 798ddfdf1f48511f29205c43baddd30b5927268b

**Comment by equalsraf** [comment]
Confirmed, it works as intended, thanks.
