### ISSUE TITLE
protoc-plugin assumes protobuf file extension is .proto

### ISSUE THREAD

**Issue by weiznich** [stepancheg/rust-protobuf#198]
While trying to translate a protobuf file with another file extension as .proto protoc-gen-rust crashes with the following backtrace: 

```
RUST_BACKTRACE=1 protoc --rust_out=. test.pb
thread 'main' panicked at 'explicit panic', protobuf-1.1.0/src/lib/strx.rs:10
stack backtrace:
   1:     0x558bf4fc473c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x558bf4fc6b9e - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x558bf4fc67a4 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x558bf4fc6f7b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x558bf4f6bf7f - std::panicking::begin_panic::hd72c3f5a7d2ab8d4
   6:     0x558bf4fb5faf - protobuf::descriptorx::proto_path_to_rust_mod::hafa8ea57a3b75135
   7:     0x558bf4fb1544 - protobuf::codegen::gen::h77101cd7554ccfae
   8:     0x558bf4fb2cec - protobuf::compiler_plugin::plugin_main::hee20f29dfc9170fb
   9:     0x558bf4fcf57a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  10:     0x558bf4fc76e6 - std::rt::lang_start::ha0568cc91d8c5b09
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  11:     0x7f9e1ede03f0 - __libc_start_main
  12:     0x558bf4f6a399 - _start
  13:                0x0 - <unknown>
--rust_out: protoc-gen-rust: Plugin failed with status code 101.
```

Translating the same file using `protoc --cpp_out . test.pb` works fine, renaming it to .proto and translate it afterwards also works fine. At least the panic message should contain an information about this.

**Comment by stepancheg** [comment]
I've added better panic message.

If you think rust-protobuf should handle files with different suffixes than `.proto`, please reopen the issue.
