### ISSUE TITLE
Panic when trying to get optional enum fields through reflection 2.24.1

### ISSUE THREAD

**Issue by mardaker** [stepancheg/rust-protobuf#564]
Hi

Latest 2.24.1 panics with following stack when trying to retrieve optional enum field:
```thread 'main' panicked at 'explicit panic', /Users/arturm/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.24.1/src/reflect/acc/v1.rs:252:18
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/arturm/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: <protobuf::reflect::acc::v1::FieldAccessorImpl<M> as protobuf::reflect::acc::v1::FieldAccessorTrait>::get_enum_generic
             at /Users/arturm/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.24.1/src/reflect/acc/v1.rs:252:18
   2: protobuf::reflect::field::FieldDescriptor::get_enum
             at /Users/arturm/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.24.1/src/reflect/field.rs:123:32
   3: proto_bug::print_fields
             at ./src/main.rs:14:21
   4: proto_bug::main
             at ./src/main.rs:25:5
```
Attached minimal sample and proto files [proto_bug.zip](https://github.com/stepancheg/rust-protobuf/files/6938237/proto_bug.zip).

Possible fix:
```
diff --git a/protobuf/src/reflect/acc/v1.rs b/protobuf/src/reflect/acc/v1.rs
index 5cf53d54..17c2d027 100644
--- a/protobuf/src/reflect/acc/v1.rs
+++ b/protobuf/src/reflect/acc/v1.rs
@@ -249,6 +249,17 @@ impl<M: Message + 'static> FieldAccessorTrait for FieldAccessorImpl<M> {
                 get_set: SingularGetSet::Enum(ref get),
                 ..
             } => get.get_enum(message_down_cast(m)),
+            FieldAccessorFunctions::Optional(ref t) => {
+                match t
+                    .get_field(message_down_cast(m))
+                    .to_option()
+                    .expect("field unset")
+                    .as_ref()
+                {
+                    ReflectValueRef::Enum(m) => m,
+                    _ => panic!("not a enum"),
+                }
+            }
             _ => panic!(),
         }
     }
```

**Comment by stepancheg** [comment]
Published 2.24.2. Thank you for the detailed repro and proposed fix!
