### ISSUE TITLE
Tests for protoc 2.27 fail

### ISSUE THREAD

**Issue by CountOmega** [stepancheg/rust-protobuf#641]
I am in the process of packaging the protoc crate for debian. The crate compiles, but the tests fail, stating the protoc binary is not found:
```
running 1 test
test test::version ... FAILED

failures:

---- test::version stdout ----
thread 'test::version' panicked at 'protoc binary not found: cannot find binary path', src/lib.rs:209:17
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.59.0/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.59.0/library/core/src/panicking.rs:116:14
   2: protoc::Protoc::from_env_path
             at /usr/share/cargo/registry/protoc-2.27.1/src/lib.rs:209:17
   3: protoc::test::version
             at /usr/share/cargo/registry/protoc-2.27.1/src/lib.rs:404:9
   4: protoc::test::version::{{closure}}
             at /usr/share/cargo/registry/protoc-2.27.1/src/lib.rs:403:5
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:227:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test::version

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass '--lib'
dh_auto_test: error: /usr/share/cargo/bin/cargo test --all returned exit code 101

```

**Comment by stepancheg** [comment]
`protoc` binary need to be in `$PATH`.

**Comment by CountOmega** [comment]
I take it protoc bin is a "virtual crate" the provides it?

**Comment by stepancheg** [comment]
`protoc` crate is an API to invoke `protoc` programmatically.

**Comment by CountOmega** [comment]
So the binary provided by [this](https://github.com/protocolbuffers/protobuf/releases/download/v21.2/protoc-21.2-linux-x86_64.zip) release?

**Comment by stepancheg** [comment]
Any version of `protoc` binary from protobuf should do.

You said you do it for Debian? I think this package provides it: https://packages.debian.org/sid/protobuf-compiler

**Comment by stepancheg** [comment]
May I ask why do you pack rust-protobuf for debian? Is there some other crate which needs it?

**Comment by CountOmega** [comment]
Ah thanks, that resolved my issue. I didn't realize `protoc` depended on an external package. `rust-cast` needs the whole proto(buf) dependency tree and an exact match for version 2.27.1.Thanks for your help.
